name: Release to Edge

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Render k8s Charm
        run: tox -e render-k8s
      - name: Pack Artifact
        run: sudo apt-get update && sudo apt-get install tar && tar czvf artifact.tar.gz metadata.yaml src/charm.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: k8s_artifact
          path: ./artifact.tar.gz

  release:
    uses: canonical/observability/.github/workflows/release-charm.yaml@artifact
    needs: render
    secrets: inherit
    with:
      charm-path: $GITHUB_WORKSPACE/main
      artifact: k8s_artifact
